Restrict Whitequark version to >= 2.6.4.0
When initializing the `Parser`, we call `emit_arg_inside_procarg0 = true`
(https://github.com/Shopify/rbi/blob/main/lib/rbi/parser.rb#L25) but this
method was added in v2.6.4.0 (https://github.com/whitequark/parser/commit/17a66bdf5712686fa8eca4a7bd10ffab45c1d754).

With the wrong version of the `parser` gem, running Tapioca results in a stack trace:

```
vendor/bundle/ruby/2.6.0/gems/rbi-0.0.13/lib/rbi/parser.rb:28:in `<class:Parser>': undefined method `emit_arg_inside_procarg0=' for Parser::Builders::Default:Class (NoMethodError)
Did you mean?  emit_procarg0=
	from vendor/bundle/ruby/2.6.0/gems/rbi-0.0.13/lib/rbi/parser.rb:20:in `<module:RBI>'
```

Signed-off-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>
Co-authored-by: Ufuk Kayserilioglu <ufuk.kayserilioglu@shopify.com>